/**
 * Test for Sheet Metal Contour Flange geometry generation
 * Validates that the feature correctly creates sweep profiles and geometries
 */

export async function test_SheetMetalContourFlange_Basic(partHistory) {
  console.log("[TEST] Starting Sheet Metal Contour Flange basic test");

  // Create a simple L-shaped sketch path
  const plane = await partHistory.newFeature("P");
  plane.inputParams.orientation = "XY"; // XY plane at Z=0

  const sketch = await partHistory.newFeature("S");
  sketch.inputParams.sketchPlane = plane.inputParams.featureID;

  // Define L-shaped path: start at origin, go right 20 units, then up 15 units
  sketch.persistentData.sketch = {
    points: [
      { id: 0, x: 0, y: 0, fixed: true },     // Origin
      { id: 1, x: 20, y: 0, fixed: false },  // Right 20 units
      { id: 2, x: 20, y: 15, fixed: false }, // Up 15 units
    ],
    geometries: [
      { id: 100, type: "line", points: [0, 1], construction: false }, // Horizontal segment
      { id: 101, type: "line", points: [1, 2], construction: false }, // Vertical segment
    ],
    constraints: [
      { id: 0, type: "⏚", points: [0] }, // Ground point 0
    ],
  };

  // Create the contour flange
  const contourFlange = await partHistory.newFeature("SM.CF");
  contourFlange.inputParams.path = [sketch.inputParams.featureID];
  contourFlange.inputParams.distance = 10;    // 10 units wide
  contourFlange.inputParams.thickness = 2;    // 2 units thick
  contourFlange.inputParams.bendRadius = 1;   // 1 unit bend radius
  contourFlange.inputParams.sheetSide = "left";
  contourFlange.inputParams.consumePathSketch = false; // Keep sketch for inspection

  console.log("[TEST] Contour flange created:", contourFlange.inputParams);

  return partHistory;
}

export async function test_SheetMetalContourFlange_StraightLine(partHistory) {
  console.log("[TEST] Starting Sheet Metal Contour Flange straight line test");

  // Create a simple straight line sketch
  const plane = await partHistory.newFeature("P");
  plane.inputParams.orientation = "XY";

  const sketch = await partHistory.newFeature("S");
  sketch.inputParams.sketchPlane = plane.inputParams.featureID;

  // Define straight line path
  sketch.persistentData.sketch = {
    points: [
      { id: 0, x: 0, y: 0, fixed: true },
      { id: 1, x: 30, y: 0, fixed: false },
    ],
    geometries: [
      { id: 100, type: "line", points: [0, 1], construction: false },
    ],
    constraints: [
      { id: 0, type: "⏚", points: [0] },
    ],
  };

  // Create the contour flange
  const contourFlange = await partHistory.newFeature("SM.CF");
  contourFlange.inputParams.path = [sketch.inputParams.featureID];
  contourFlange.inputParams.distance = 5;
  contourFlange.inputParams.thickness = 1;
  contourFlange.inputParams.bendRadius = 0; // No bends for straight line
  contourFlange.inputParams.sheetSide = "right";
  contourFlange.inputParams.consumePathSketch = false;

  console.log("[TEST] Straight line contour flange created");

  return partHistory;
}

function findContourFlangeFeature(partHistory) {
  const entry = partHistory.features.find((f) => f?.type === "SM.CF");
  if (!entry) throw new Error("Contour flange feature missing from history");
  const featureId = entry?.inputParams?.featureID;
  if (!featureId) throw new Error("Contour flange feature missing featureID");
  return featureId;
}

function collectContourFlangeSolids(partHistory, featureId) {
  const children = Array.isArray(partHistory.scene?.children) ? partHistory.scene.children : [];
  return children.filter((obj) => {
    if (!obj || obj.type !== "SOLID") return false;
    if (obj?.owningFeatureID && String(obj.owningFeatureID) === String(featureId)) return true;
    return !!(obj?.name && obj.name.includes(featureId));
  });
}

function validateContourFlangeGeometry(partHistory, label) {
  const featureId = findContourFlangeFeature(partHistory);
  const solids = collectContourFlangeSolids(partHistory, featureId);
  if (!solids.length) {
    throw new Error(`[${label}] No solids were generated by the contour flange feature`);
  }

  let triCount = 0;
  for (const solid of solids) {
    const triVerts = Array.isArray(solid?._triVerts) ? solid._triVerts.length : 0;
    triCount += Math.floor(triVerts / 3);
  }

  if (triCount === 0) {
    throw new Error(`[${label}] Generated geometry has no triangles`);
  }
}

export async function afterRun_SheetMetalContourFlange_Basic(partHistory) {
  validateContourFlangeGeometry(partHistory, "contour_flange_basic");
}

export async function afterRun_SheetMetalContourFlange_StraightLine(partHistory) {
  validateContourFlangeGeometry(partHistory, "contour_flange_straight");
}
