import type { WorkbenchDefinition } from './index.js';

export const SHEET_METAL_WORKBENCH = {
  id: 'SHEET_METAL',
  label: 'Sheet Metal',
  featureTypes: [
    'D',
    'P',
    'S',
    'F',
    'SM.TAB',
    'SM.CF',
    'SM.F',
    'SM.HEM',
    'SM.CUTOUT',
    'H',
  ],
  contextFamilies: {
    features: true,
    assemblyConstraints: false,
    pmiAnnotations: false,
  },
  sidePanels: {
    assemblyConstraints: false,
    pmiViews: true,
  },
  toolbarButtons: [
    'new',
    'save',
    'saveAs',
    'zoomToFit',
    'wireframe',
    'import',
    'export',
    'share',
    'sheetEditor',
    'sheetMetalFlatExport',
    'sheetMetalDebug',
    'about',
    'historyTestSnippet',
    'scriptRunner',
    'undo',
    'redo',
    'tests',
    'selectionState',
  ],
} satisfies WorkbenchDefinition;
