export const SURFACING_WORKBENCH = {
  id: 'SURFACING',
  label: 'Surfacing',
  featureTypes: [
    'D',
    'P',
    'S',
    'SP',
    'LOFT',
    'SW',
    'R',
    'O.F',
    'NURBS',
    'POLY',
    'SWS',
    'M',
    'XFORM',
    'RM',
    'CE',
    'ES',
    'OVL',
    'RM',
    'O.S',
  ],
  contextFamilies: {
    features: true,
    assemblyConstraints: false,
    pmiAnnotations: false,
  },
  sidePanels: {
    assemblyConstraints: false,
    pmiViews: true,
  },
  toolbarButtons: [
    'home',
    'new',
    'save',
    'zoomToFit',
    'wireframe',
    'import',
    'export',
    'share',
    'sheetEditor',
    'about',
    'historyTestSnippet',
    'scriptRunner',
    'undo',
    'redo',
    'tests',
    'selectionState',
  ],
};
