import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";

export const MANIFOLD_SOURCE_NPM = "npm";
export const MANIFOLD_SOURCE_LOCAL = "local";

const VALID_SOURCES = new Set([MANIFOLD_SOURCE_NPM, MANIFOLD_SOURCE_LOCAL]);

const rootDir = process.cwd();
const settingsPath = path.join(rootDir, "settings", "manifold-source.json");
const generatedPath = path.join(rootDir, "src", "generated", "manifoldSource.js");

const normalizeSource = (value) =>
  VALID_SOURCES.has(value) ? value : MANIFOLD_SOURCE_NPM;

export function readManifoldSource() {
  const envSource = String(process.env.BREP_MANIFOLD_SOURCE || "").trim();
  if (VALID_SOURCES.has(envSource)) return envSource;

  if (!existsSync(settingsPath)) return MANIFOLD_SOURCE_NPM;
  try {
    const data = JSON.parse(readFileSync(settingsPath, "utf-8"));
    return normalizeSource(String(data?.source || ""));
  } catch {
    return MANIFOLD_SOURCE_NPM;
  }
}

export function writeManifoldSource(source) {
  const normalized = normalizeSource(source);
  mkdirSync(path.dirname(settingsPath), { recursive: true });
  writeFileSync(settingsPath, `${JSON.stringify({ source: normalized }, null, 2)}\n`, "utf-8");

  mkdirSync(path.dirname(generatedPath), { recursive: true });
  writeFileSync(
    generatedPath,
    `// Auto-generated by scripts/setManifoldSource.js
export const MANIFOLD_RUNTIME_SOURCE = ${JSON.stringify(normalized)};
export const MANIFOLD_RUNTIME_IS_LOCAL = MANIFOLD_RUNTIME_SOURCE === "local";
export const MANIFOLD_RUNTIME_IS_NPM = MANIFOLD_RUNTIME_SOURCE === "npm";
`,
    "utf-8"
  );

  return normalized;
}
